# Generated by Django 4.2.4 on 2023-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadasto_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espaco_comum', models.CharField(choices=[('salao_de_festas', 'Salão de Festas'), ('campo_de_futebol', 'Campo de Futebol'), ('espaco_gourmet', 'Espaço Gourmet'), ('quadra_de_tenis', 'Quadra de Tênis')], max_length=20)),
                ('data_reserva', models.DateField()),
            ],
        ),
    ]
