# Generated by Django 4.2.4 on 2023-10-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nome_usuario", models.CharField(max_length=50, unique=True)),
                ("apartamento", models.CharField(max_length=10)),
                ("tipo_usuario", models.CharField(max_length=20)),
                ("senha", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "registro_usuario",
            },
        ),
    ]
