# Generated by Django 4.2.4 on 2023-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('visitante', 'Visitante'), ('funcionario', 'Funcionário')], max_length=20)),
            ],
            options={
                'db_table': 'cadastro_visita_ou_funcionario',
            },
        ),
    ]
