# Generated by Django 4.2.4 on 2023-11-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="registro_funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.TextField(max_length=50)),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("gerente", "Gerente"),
                            ("zelador", "Zelador"),
                            ("porteiro", "Porteiro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("contato", models.TextField(max_length=20)),
                (
                    "horario",
                    models.CharField(
                        choices=[
                            ("matutino", "Matutino"),
                            ("vespertino", "Vespertino"),
                            ("noturno", "Noturno"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "db_table": "registro_funcionario",
            },
        ),
    ]
