name: Build and deploy Python app to Azure Web App - appeasycond

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Configurar ambiente virtual
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar migrações do Django
        run: |
          python manage.py migrate

      - name: Rodar testes do Django
        run: |
          python -m unittest discover -v

      - name: Limpar
        run: |
          rm -rf venv  # Remover ambiente virtual
          rm -f db.sqlite3  # Remover arquivo de banco de dados SQLite
          rm -f .env  # Remover arquivo de ambiente, se presente

      - name: Upload de artefato para trabalhos de deploy
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: .
          exclude: |
            venv/
            __pycache__/
            .git/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download de artefato do trabalho de build
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Instalar Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          CHROMEDRIVER_VERSION=119.0.6045.104
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          google-chrome-stable --version
          chromedriver --version

      - name: 'Deploy para o Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'appeasycond'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CF01664E481249B6A8A451A45BC3078B }}
