# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - EasyCond

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Certifique-se de que a versão seja compatível com seu projeto Django.

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r EasyCond/requirements.txt  # Verifique o caminho para o requirements.txt.

      - name: Cleaning testing files
        run: |
          cd easy_cond/
          rm .env
          cd ..

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            EasyCond
            !venv/  # Exclui o ambiente virtual.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EasyCond'  # Nome correto do seu aplicativo na Azure.
          slot-name: 'Production'  # Nome correto do seu slot, se aplicável.
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_03CB21F38F9E4B2D96106B86A2FED13B }}  # Nome correto do seu segredo de chave de publicação.
