name: Run End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

    - name: Download and Install ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=119.0.6045.105
        curl -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    - name: Limpar Cache
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get clean

    - name: Configure Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: python -m unittest discover -v e2e_tests/
