# Generated by Django 4.2.4 on 2023-10-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="registro_denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        choices=[
                            ("academia", "Academia"),
                            ("campo_de_futebol", "Campo de Futebol"),
                            ("quadra_de_tenis", "Quadra de Tênis"),
                            ("espaco_gourmet", "Espaço Gourmet"),
                            ("salao_de_festas", "Salão de Festas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_infracao",
                    models.CharField(
                        choices=[
                            ("barulhe_excessivo", "Barulho Excessivo"),
                            ("dano_ao_patrimõnio", "Dano ao Patrimônio"),
                            ("desrespeito_as_normas", "Desreipeito às Normas"),
                        ],
                        max_length=30,
                    ),
                ),
                ("unidade", models.CharField(max_length=4)),
                ("comentario", models.TextField()),
            ],
            options={
                "db_table": "registro_denuncia",
            },
        ),
    ]
